apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: ray
  name: ray-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ray-worker
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
